---
- name: Verify
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: Reboot and reconnect
      when:
        - ansible_facts.virtualization_type not in ["container", "docker", "podman"]
      block:
        - name: Reboot host
          become: true
          ansible.builtin.reboot:

        - name: Wait for the host and reconnect
          ansible.builtin.wait_for:
            port: 22
            host: "{{ (ansible_facts.ssh_host | default(ansible_facts.host)) | default(inventory_hostname) }}"
            delay: 10
            timeout: 120

    - name: Include default vars
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions:
          - yml

    - name: Include host vars
      ansible.builtin.include_vars:
        file: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/inventory/host_vars/{{ ansible_facts.hostname }}"

    - name: Get PAM version
      block:
        - name: Gather package facts
          ansible.builtin.package_facts:
            manager: auto

        - name: Get libpam version in Debian family
          ansible.builtin.set_fact:
            pam_version: "{{ ansible_facts.packages['libpam-modules'][0].version }}"
          when:
            - ansible_facts.os_family == "Debian"
            - "'libpam-modules' in ansible_facts.packages"

        - name: Get libpam version in RedHat family
          ansible.builtin.set_fact:
            pam_version: "{{ ansible_facts.packages['pam'][0].version }}"
          when:
            - ansible_facts.os_family in ["RedHat", "Suse"]
            - "'pam' in ansible_facts.packages"

    - name: Set hashing algorithm for password (yescrypt|sha512)
      ansible.builtin.set_fact:
        password_algorithm: "{{ 'yescrypt' if (pam_version is version('1.4.0', '>=')) else 'sha512' }}"

    - name: Verify login.defs settings
      become: true
      ansible.builtin.shell: grep "^{{ item }}$" /etc/login.defs
      register: login_defs
      changed_when: false
      failed_when: login_defs.rc != 0
      with_items:
        - ENCRYPT_METHOD {{ password_algorithm | upper }}
        - FAILLOG_ENAB yes
        - HOME_MODE {{ login_defs.home_mode }}
        - LOG_OK_LOGINS yes
        - LOGIN_RETRIES {{ login_defs.login_retries }}
        - LOGIN_TIMEOUT {{ login_defs.login_timeout }}
        - PASS_MAX_DAYS {{ login_defs.pass_max_days }}
        - PASS_MIN_DAYS {{ login_defs.pass_min_days }}
        - PASS_WARN_AGE {{ login_defs.pass_warn_age }}
        - SHA_CRYPT_MAX_ROUNDS 65536
        - SHA_CRYPT_MIN_ROUNDS 10000
        - SU_NAME su
        - SYSLOG_SG_ENAB yes
        - SYSLOG_SU_ENAB yes
        - UMASK {{ login_defs.umask_value }}
        - USERGROUPS_ENAB {{ 'yes' if login_defs.usergroups_enabled else 'no' }}
