---
- name: Verify
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: Reboot and reconnect
      when:
        - ansible_facts.virtualization_type not in ["container", "docker", "podman"]
      block:
        - name: Reboot host
          become: true
          ansible.builtin.reboot:

        - name: Wait for the host and reconnect
          ansible.builtin.wait_for:
            port: 22
            host: "{{ (ansible_facts.ssh_host | default(ansible_facts.host)) | default(inventory_hostname) }}"
            delay: 10
            timeout: 120

    - name: Include default vars
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions:
          - yml

    - name: Include host vars
      ansible.builtin.include_vars:
        file: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/inventory/host_vars/{{ ansible_facts.hostname }}"

    - name: Check sudo type
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          sudo --version | head -n 1
      args:
        executable: /bin/bash
      register: sudo_type_check
      changed_when: false

    - name: Set fact for sudo type
      ansible.builtin.set_fact:
        sudo_rs_present: "{{ 'sudo-rs' in sudo_type_check.stdout or 'sudo-rs' in sudo_type_check.stderr }}"

    - name: Debug sudo type
      ansible.builtin.debug:
        msg: "sudo-rs is present: {{ sudo_rs_present }}"

    - name: Register sudo settings
      become: true
      ansible.builtin.command:
        cmd: grep -REvh '#|^$' /etc/sudoers /etc/sudoers.d/
      register: sudo_settings_output
      changed_when: false
      failed_when: sudo_settings_output.rc != 0

    - name: Assert sudo settings output
      ansible.builtin.assert:
        that:
          - "'use_pty' in sudo_settings_output.stdout"
          - "'logfile=/var/log/sudo.log' in sudo_settings_output.stdout"
          - "'!pwfeedback' in sudo_settings_output.stdout"
          - "'!visiblepw' in sudo_settings_output.stdout"
          - "'passwd_timeout=1' in sudo_settings_output.stdout"
          - "'timestamp_timeout=5' in sudo_settings_output.stdout"
          - "'timestamp_type=tty' in sudo_settings_output.stdout"
          - "'!rootpw' in sudo_settings_output.stdout"
          - "'!runaspw' in sudo_settings_output.stdout"
          - "'!targetpw' in sudo_settings_output.stdout"
      when:
        - not sudo_rs_present

    - name: Assert sudo-rs settings
      ansible.builtin.assert:
        that:
          - "'use_pty' in sudo_settings_output.stdout"
          - "'!pwfeedback' in sudo_settings_output.stdout"
          - "'!visiblepw' in sudo_settings_output.stdout"
          - "'passwd_timeout=1' in sudo_settings_output.stdout"
          - "'timestamp_timeout=5' in sudo_settings_output.stdout"
          - "'!rootpw' in sudo_settings_output.stdout"
          - "'!targetpw' in sudo_settings_output.stdout"
      when:
        - sudo_rs_present

    - name: Assert su group configuration
      become: true
      ansible.builtin.command:
        cmd: grep -Ev '#|^$' /etc/pam.d/su
      register: su_group_check
      changed_when: false
      failed_when: su_group_check.rc != 0

    - name: Assert su group configuration output
      ansible.builtin.assert:
        that:
          - "'auth required pam_wheel.so use_uid group=sugroup' in su_group_check.stdout_lines"
