---
argument_specs:
  main:
    short_description: hosts.allow and hosts.deny management
    description:
      - hosts.allow and hosts.deny management.
    author:
      - "Thomas Sjögren (@konstruktoid)"
    options:
      hosts_allow_template:
        description: "/etc/hosts.allow template location."
        type: "path"
        default: "etc/hosts.allow.j2"
      hosts_deny_template:
        description: "/etc/hosts.deny template location."
        type: "path"
        default: "etc/hosts.deny.j2"
