---
- name: Verify
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: Reboot and reconnect
      when:
        - ansible_facts.virtualization_type not in ["container", "docker", "podman"]
      block:
        - name: Reboot host
          become: true
          ansible.builtin.reboot:

        - name: Wait for the host and reconnect
          ansible.builtin.wait_for:
            port: 22
            host: "{{ (ansible_facts.ssh_host | default(ansible_facts.host)) | default(inventory_hostname) }}"
            delay: 10
            timeout: 120

    - name: Include default vars
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions:
          - yml

    - name: Include host vars
      ansible.builtin.include_vars:
        file: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/inventory/host_vars/{{ ansible_facts.hostname }}"

    - name: Verify AIDE configuration
      become: true
      block:
        - name: Get AIDE include config
          ansible.builtin.command:
            cmd: grep -m1 -E "^@@(x_include|include) \/" "{{ '/etc/aide/aide.conf' if ansible_facts.os_family == 'Debian' else '/etc/aide.conf' }}"
          register: grep_aide_include
          changed_when: false
          failed_when: false
          check_mode: false

        - name: Debug AIDE include grep
          ansible.builtin.debug:
            msg: "{{ grep_aide_include.stdout_lines }}"

        - name: Set AIDE include as fact
          ansible.builtin.set_fact:
            aide_include_d: "{{ 'false' if grep_aide_include.rc != 0 else grep_aide_include.stdout.split()[1] }}"

        - name: Debug AIDE include path
          ansible.builtin.debug:
            msg: "{{ aide_include_d }}"

        - name: Check if AIDE include directory exits
          ansible.builtin.stat:
            path: "{{ aide_include_d }}"
          register: aide_config_d

        - name: AIDE config check
          become: true
          ansible.builtin.command:
            cmd: aide --config-check --config="{{ '/etc/aide/aide.conf' if ansible_facts.os_family == 'Debian' else '/etc/aide.conf' }}"
          register: aide_config
          changed_when: false
          failed_when: aide_config.rc != 0

        - name: Get AIDE settings
          ansible.builtin.command:
            cmd: grep -Ev "#|^$" "{{ '/etc/aide/aide.conf' if ansible_facts.os_family == 'Debian' else '/etc/aide.conf' }}"
          register: aide_settings
          changed_when: false
          failed_when: aide_settings.rc != 0
          when:
            - not aide_config_d.stat.exists

        - name: Print AIDE settings
          ansible.builtin.debug:
            msg: "{{ aide_settings.stdout_lines }}"
          when:
            - not aide_config_d.stat.exists

        - name: Assert AIDE settings
          ansible.builtin.assert:
            that:
              - "'/usr/sbin/auditctl p+i+n+u+g+s+b+acl+xattrs+sha512' in aide_settings.stdout"
              - "'/usr/sbin/auditd p+i+n+u+g+s+b+acl+xattrs+sha512' in aide_settings.stdout"
              - "'/usr/sbin/ausearch p+i+n+u+g+s+b+acl+xattrs+sha512' in aide_settings.stdout"
              - "'/usr/sbin/aureport p+i+n+u+g+s+b+acl+xattrs+sha512' in aide_settings.stdout"
              - "'/usr/sbin/autrace p+i+n+u+g+s+b+acl+xattrs+sha512' in aide_settings.stdout"
              - "'/usr/sbin/augenrules p+i+n+u+g+s+b+acl+xattrs+sha512' in aide_settings.stdout"
              - "'/usr/sbin/audispd p+i+n+u+g+s+b+acl+xattrs+sha512' in aide_settings.stdout"
              - "'!/var/lib/docker' in aide_settings.stdout"
              - "'!/var/lib/lxcfs' in aide_settings.stdout"
              - "'!/var/lib/private/systemd' in aide_settings.stdout"
              - "'!/var/log/audit' in aide_settings.stdout"
          when:
            - not aide_config_d.stat.exists

        - name: Get AIDE settings from includes
          ansible.builtin.command:
            cmd: grep -REhv --include="99_*" "#|^$" "{{ aide_include_d }}"
          register: aide_settings
          changed_when: false
          failed_when: aide_settings.rc != 0
          when:
            - aide_config_d.stat.exists

        - name: Print AIDE settings from includes
          ansible.builtin.debug:
            msg: "{{ aide_settings.stdout_lines }}"
          when:
            - aide_config_d.stat.exists

        - name: Assert AIDE settings from includes
          ansible.builtin.assert:
            that:
              - "'/usr/sbin/auditctl p+i+n+u+g+s+b+acl+xattrs+sha512' in aide_settings.stdout"
              - "'/usr/sbin/auditd p+i+n+u+g+s+b+acl+xattrs+sha512' in aide_settings.stdout"
              - "'/usr/sbin/ausearch p+i+n+u+g+s+b+acl+xattrs+sha512' in aide_settings.stdout"
              - "'/usr/sbin/aureport p+i+n+u+g+s+b+acl+xattrs+sha512' in aide_settings.stdout"
              - "'/usr/sbin/autrace p+i+n+u+g+s+b+acl+xattrs+sha512' in aide_settings.stdout"
              - "'/usr/sbin/augenrules p+i+n+u+g+s+b+acl+xattrs+sha512' in aide_settings.stdout"
              - "'/usr/sbin/audispd p+i+n+u+g+s+b+acl+xattrs+sha512' in aide_settings.stdout"
              - "'!/var/lib/docker' in aide_settings.stdout"
              - "'!/var/lib/lxcfs' in aide_settings.stdout"
              - "'!/var/lib/private/systemd' in aide_settings.stdout"
              - "'!/var/log/audit' in aide_settings.stdout"
              - "'!/var/log/journal' in aide_settings.stdout"
          when:
            - aide_config_d.stat.exists
