---
argument_specs:
  main:
    short_description: Path hardening for AlmaLinux, Debian and Ubuntu.
    description:
      - "This Ansible role hardens the PATH variable for all users on AlmaLinux, Debian and Ubuntu."
    author:
      - konstruktoid
    options:
      initpath_sh_template:
        description: "profile initpath.sh template location."
        type: "path"
        default: "etc/profile.d/initpath.sh.j2"
