---
- name: Configure scheduled command services
  become: true
  block:
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Remove cron.deny and at.deny
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/at.deny
        - /etc/cron.deny

    - name: Check whether cron and at allow files exist
      ansible.builtin.stat:
        path: "{{ item }}"
      loop:
        - /etc/at.allow
        - /etc/cron.allow
      register: cron_at_allow_files

    - name: Clean cron and at
      ansible.builtin.lineinfile:
        path: "{{ item.item }}"
        regexp: ^(?!root).*$
        state: absent
      loop: "{{ cron_at_allow_files.results }}"
      when:
        - item.stat.exists

    - name: Allow root cron and at
      ansible.builtin.lineinfile:
        path: "{{ item }}"
        line: root
        mode: "0600"
        state: present
        create: true
        owner: root
        group: root
      loop:
        - /etc/at.allow
        - /etc/cron.allow

    - name: Mask atd
      ansible.builtin.systemd_service:
        name: atd
        masked: true
        enabled: false
        state: stopped
      register: mask_atd
      when:
        - "'atd' in ansible_facts.services"
        - ansible_facts.virtualization_type not in ["container", "docker", "podman"]

    - name: Set cron permissions
      ansible.builtin.file:
        path: "{{ item }}"
        mode: "0700"
        owner: root
        group: root
        state: directory
      register: cron_perm
      failed_when:
        - cron_perm is not success
        - not 'is absent, cannot continue' in cron_perm.msg
      loop:
        - /etc/cron.d
        - /etc/cron.daily
        - /etc/cron.hourly
        - /etc/cron.weekly
        - /etc/cron.monthly

    - name: Check whether /etc/crontab exists
      ansible.builtin.stat:
        path: /etc/crontab
      register: crontab_stat

    - name: Set crontab permissions
      ansible.builtin.file:
        path: /etc/crontab
        mode: "0600"
        owner: root
        group: root
      when:
        - crontab_stat.stat.exists
