---
# Configure automatic updates.
automatic_updates:
  only_security: true # If True, only security updates will be installed automatically.
  reboot: false # If True, it will reboot the system if needed.
  reboot_from_time: "2:00" # If system reboot is enabled, the variable sets the reboot time, with added random minutes from C(reboot_time_margin_mins).
  reboot_time_margin_mins: 20 # Add minutes to the reboot time, set using C(reboot_from_time).
  custom_origins: [] # Add custom origins to unattended upgrades through a list of strings.

# APT unattended-upgrades for custom origins template location.
unattended_upgrades_custom_origins_template: "etc/apt/apt.conf.d/53unattended-upgrades-custom-origins.j2"

# APT unattended-upgrades template location.
unattended_upgrades_template: "etc/apt/apt.conf.d/52unattended-upgrades-local.j2"
