---
# A list of addresses to use as system DNS servers.
dns: ["1.1.1.2", "9.9.9.9"]
# Set the DNS over TLS mode for systemd-resolved.
dns_over_tls: "opportunistic"

# Set the DNSSEC mode for systemd-resolved.
dnssec: "allow-downgrade"

# A list of addresses to use as the fallback DNS servers.
fallback_dns: ["1.0.0.2", "149.112.112.112"]

# Enable or disable Link-Local Multicast Name Resolution.
llmnr: "no"

# Enable or disable multicast DNS resolution, on by default per-link since
# systemd v253.
multicast_dns: "no"

# Systemd resolved.conf template location.
resolved_conf_template: "etc/systemd/resolved.conf.j2"
