---
- name: Generate auditd rules
  become: true
  ansible.builtin.command:
    cmd: augenrules
  register: augenrules_handler
  changed_when:
    - augenrules_handler.rc == 0

- name: Enable auditd
  become: true
  ansible.builtin.service:
    name: auditd
    enabled: true
  when:
    - ansible_facts.virtualization_type not in ["container", "docker", "podman"]

- name: Update GRUB
  become: true
  ansible.builtin.command:
    cmd: update-grub
  register: update_grub
  changed_when: update_grub.rc == 0
  when:
    - ansible_facts.virtualization_type not in ["container", "docker", "podman"]

- name: Update GRUB2
  become: true
  ansible.builtin.command:
    cmd: grub2-mkconfig
  register: update_grub2
  changed_when: update_grub2.rc == 0
  when:
    - ansible_facts.virtualization_type not in ["container", "docker", "podman"]
