---
- name: Stat and manage /etc/security/access.conf
  become: true
  block:
    - name: Stat access.conf
      ansible.builtin.stat:
        path: /etc/security/access.conf
      register: security_access_conf

    - name: Remove non-standard root entries from access.conf
      ansible.builtin.replace:
        path: /etc/security/access.conf
        regexp: '^(?:\+:root:(?!127\.0\.0\.1 ::1$)|-:root:(?!ALL$)).*\n?'
        replace: ''
      when:
        - security_access_conf.stat.exists

    - name: Configure root access entries in access.conf
      ansible.builtin.blockinfile:
        path: /etc/security/access.conf
        block: |
          +:root:127.0.0.1 ::1
          -:root:ALL
        marker: "# {mark} ANSIBLE MANAGED ROOT ACCESS"
        insertbefore: BOF
      when:
        - security_access_conf.stat.exists

- name: Stat and clean /etc/securetty
  become: true
  block:
    - name: Ensure /etc/securetty is empty
      ansible.builtin.copy:
        dest: /etc/securetty
        content: ""
        owner: root
        group: root
        mode: "0000"

- name: Gather all systemd unit info
  community.general.systemd_info:
    unitname:
      - debug-shell.service
  register: debug_shell_service
  failed_when:
    - debug_shell_service is failed
    - "'No units match' not in debug_shell_service.msg"
  when:
    - ansible_facts.virtualization_type not in ["container", "docker", "podman"]

- name: Mask systemd debug-shell
  become: true
  ansible.builtin.systemd_service:
    name: debug-shell.service
    masked: true
    enabled: false
    state: stopped
  when:
    - ansible_facts.virtualization_type not in ["container", "docker", "podman"]
    - debug_shell_service is success
