---
- name: Configure /etc/security/access.conf for root
  become: true
  ansible.builtin.blockinfile:
    path: /etc/security/access.conf
    block: |
      +:root:127.0.0.1 ::1
      -:root:ALL
    marker: "# {mark} ANSIBLE MANAGED ROOT ACCESS"

- name: Stat and clean /etc/securetty
  become: true
  block:
    - name: Ensure /etc/securetty is empty
      ansible.builtin.copy:
        dest: /etc/securetty
        content: ""
        owner: root
        group: root
        mode: "0000"

- name: Gather all systemd unit info
  community.general.systemd_info:
    unitname:
      - debug-shell.service
  register: debug_shell_service
  failed_when:
    - debug_shell_service is failed
    - "'No units match' not in debug_shell_service.msg"
  when:
    - ansible_facts.virtualization_type not in ["container", "docker", "podman"]

- name: Mask systemd debug-shell
  become: true
  ansible.builtin.systemd_service:
    name: debug-shell.service
    masked: true
    enabled: false
    state: stopped
  when:
    - ansible_facts.virtualization_type not in ["container", "docker", "podman"]
    - debug_shell_service is success
