---
- name: Verify
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: Reboot and reconnect
      when:
        - ansible_facts.virtualization_type not in ["container", "docker", "podman"]
      block:
        - name: Reboot host
          become: true
          ansible.builtin.reboot:

        - name: Wait for the host and reconnect
          ansible.builtin.wait_for:
            port: 22
            host: "{{ (ansible_facts.ssh_host | default(ansible_facts.host)) | default(inventory_hostname) }}"
            delay: 10
            timeout: 120

    - name: Include default vars
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions:
          - yml

    - name: Include host vars
      ansible.builtin.include_vars:
        file: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/inventory/host_vars/{{ ansible_facts.hostname }}"

    - name: Gather installed package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Set fact if usbguard is installed
      ansible.builtin.set_fact:
        usbguard_installed: "{{ 'usbguard' in ansible_facts.packages }}"

    - name: Verify blocked blacklisted kernel modules
      when:
        - ansible_facts.virtualization_type not in ["container", "docker", "podman"]
      block:
        - name: Verify blocked blacklisted kernel modules
          environment:
            PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          ansible.builtin.shell: |
            set -o pipefail
            grep -F 'install {{ item }} /bin/true' /etc/modprobe.d/blacklist-blocked.conf
          args:
            executable: /bin/bash
          changed_when: false
          with_items:
            - "{{ (fs_modules_blocklist + net_modules_blocklist + (misc_modules_usbguard if usbguard_installed else misc_modules_blocklist)) | sort | unique }}"
