---
- name: Verify
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: Reboot and reconnect
      when:
        - ansible_facts.virtualization_type not in ["container", "docker", "podman"]
      block:
        - name: Reboot host
          become: true
          ansible.builtin.reboot:

        - name: Wait for the host and reconnect
          ansible.builtin.wait_for:
            port: 22
            host: "{{ (ansible_facts.ssh_host | default(ansible_facts.host)) | default(inventory_hostname) }}"
            delay: 10
            timeout: 120

    - name: Include default vars
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions:
          - yml

    - name: Include host vars
      ansible.builtin.include_vars:
        file: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/inventory/host_vars/{{ ansible_facts.hostname }}"

    - name: Loop over motd, issue and issue.net to stat
      ansible.builtin.stat:
        path: "/etc/{{ item }}"
      loop:
        - motd
        - issue
        - issue.net
      register: stat_results

    - name: Assert the motd, issue and issue.net file owner and permissions
      ansible.builtin.assert:
        that:
          - item.stat.exists
          - item.stat.pw_name == 'root'
          - item.stat.mode == '0644'
      loop: "{{ stat_results.results }}"
      loop_control:
        label: "{{ item.stat.path }}"
