---
- name: Verify
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: Reboot and reconnect
      when:
        - ansible_facts.virtualization_type not in ["container", "docker", "podman"]
      block:
        - name: Reboot host
          become: true
          ansible.builtin.reboot:

        - name: Wait for the host and reconnect
          ansible.builtin.wait_for:
            port: 22
            host: "{{ (ansible_facts.ssh_host | default(ansible_facts.host)) | default(inventory_hostname) }}"
            delay: 10
            timeout: 120

    - name: Include default vars
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions:
          - yml

    - name: Include host vars
      ansible.builtin.include_vars:
        file: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/inventory/host_vars/{{ ansible_facts.hostname }}"

    - name: Get Apport settings
      ansible.builtin.command:
        cmd: grep -Ev '#|^$' /etc/default/apport
      changed_when: false
      register: apport_settings
      failed_when:
        - apport_settings.rc != 0
        - apport_settings.rc != 2

    - name: Assert Apport is disabled
      ansible.builtin.assert:
        that:
          - "'enabled=0' in apport_settings.stdout"
      failed_when:
        - apport_settings.rc != 0
        - apport_settings.rc != 2
