---
- name: Verify
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: Reboot and reconnect
      when:
        - ansible_facts.virtualization_type not in ["container", "docker", "podman"]
      block:
        - name: Reboot host
          become: true
          ansible.builtin.reboot:

        - name: Wait for the host and reconnect
          ansible.builtin.wait_for:
            port: 22
            host: "{{ (ansible_facts.ssh_host | default(ansible_facts.host)) | default(inventory_hostname) }}"
            delay: 10
            timeout: 120

    - name: Include default vars
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions:
          - yml

    - name: Include host vars
      ansible.builtin.include_vars:
        file: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/inventory/host_vars/{{ ansible_facts.hostname }}"

    - name: Verify logind settings
      ansible.builtin.shell: |
        set -o pipefail
        systemd-analyze cat-config systemd/logind.conf | grep "^{{ item }}"
      args:
        executable: /bin/bash
      register: logind_conf
      changed_when: false
      failed_when: logind_conf.rc != 0
      with_items:
        - KillUserProcesses={{ 'true' if logind.killuserprocesses else 'false' }}
        - KillExcludeUsers={{ logind.killexcludeusers | join(' ') }}
        - IdleAction={{ logind.idleaction }}
        - IdleActionSec={{ logind.idleactionsec }}
        - RemoveIPC={{ 'true' if logind.removeipc else 'false' }}
      when:
        - ansible_facts.virtualization_type not in ["container", "docker", "podman"]

    - name: Verify StopIdleSessionSec setting
      ansible.builtin.shell: |
        set -o pipefail
        systemd-analyze cat-config systemd/logind.conf | grep "^{{ item }}"
      args:
        executable: /bin/bash
      register: stopidlesession
      changed_when: false
      failed_when: stopidlesession.rc != 0
      with_items:
        - StopIdleSessionSec={{ session_timeout }}
      when:
        - ansible_facts.virtualization_type not in ["container", "docker", "podman"]
        - ansible_facts.systemd.version | int >= 252
