---
- name: Verify
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: Reboot and reconnect
      when:
        - ansible_facts.virtualization_type not in ["container", "docker", "podman"]
      block:
        - name: Reboot host
          become: true
          ansible.builtin.reboot:

        - name: Wait for the host and reconnect
          ansible.builtin.wait_for:
            port: 22
            host: "{{ (ansible_facts.ssh_host | default(ansible_facts.host)) | default(inventory_hostname) }}"
            delay: 10
            timeout: 120

    - name: Include default vars
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions:
          - yml

    - name: Include host vars
      ansible.builtin.include_vars:
        file: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/inventory/host_vars/{{ ansible_facts.hostname }}"

    - name: Set sysctl configuration directory as fact
      block:
        - name: Stat /usr/lib/sysctl.d/
          ansible.builtin.stat:
            path: /usr/lib/sysctl.d/
          register: usr_lib_sysctl_d

        - name: Set /usr/lib/sysctl.d/ existence fact
          ansible.builtin.set_fact:
            usr_lib_sysctl_d_dir: "{{ true if usr_lib_sysctl_d.stat.exists else false }}"

        - name: Set sysctl_conf_dir fact based on /usr/lib/sysctl.d/ existence
          ansible.builtin.set_fact:
            sysctl_conf_dir: "{{ '/usr/lib/sysctl.d' if usr_lib_sysctl_d_dir else '/etc/sysctl.d' }}"

    - name: Verify IPv6 settings in GRUB and sysctl
      become: true
      when:
        - ansible_facts.virtualization_type not in ["container", "docker", "podman"]
      block:
        - name: Verify RedHat GRUB IPv6 settings
          ansible.builtin.shell:
            cmd: |
              set -o pipefail
              grubby --info="/boot/vmlinuz-$(uname -r)" | grep "ipv6.disable=1"
          register: audit_grubenv
          changed_when: false
          failed_when: audit_grubenv.rc != 0
          when:
            - ansible_facts.os_family == "RedHat"

        - name: Verify Debian GRUB IPv6 settings
          ansible.builtin.shell:
            cmd: grep "linux.*ipv6.disable=1" /boot/grub/grub.cfg
          register: audit_grub_cfg
          changed_when: false
          failed_when: audit_grub_cfg.rc != 0
          when:
            - ansible_facts.os_family == "Debian"

        - name: Verify IPv6 sysctl configuration
          ansible.builtin.shell: |
            set -o pipefail
            /lib/systemd/systemd-sysctl --cat-config | grep "^{{ item }}$"
          args:
            executable: /bin/bash
          register: sysctl_ipv6_config
          changed_when: false
          with_items:
            - net.ipv6.conf.all.disable_ipv6 = 1
            - net.ipv6.conf.default.disable_ipv6 = 1
