---
# This option controls who can access the information in C(/proc/pid) directories
hide_pid: 2

# Specifies the GID of the group that can access (/proc/pid) directories when C(hide_pid) is set to 2.
process_group: 0

# tmp.mount template location.
tmp_mount_template: "etc/systemd/system/tmp.mount.j2"
