---
galaxy_info:
  role_name: sudo
  author: konstruktoid
  description: SUDO configuration and hardening.
  license: apache
  min_ansible_version: "2.18"
  platforms:
    - name: Debian
      versions:
        - trixie
    - name: EL
      versions:
        - "10"
    - name: Ubuntu
      versions:
        - resolute
  galaxy_tags:
    - almalinux
    - cis
    - debian
    - disa
    - hardening
    - security
    - system
    - sudo
    - ubuntu
