---
galaxy_info:
  role_name: adduser
  author: konstruktoid
  description: Configure adduser and useradd.
  license: apache
  min_ansible_version: "2.18"
  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: EL
      versions:
        - "9"
        - "10"
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - adduser
    - almalinux
    - centos
    - cis
    - debian
    - disa
    - hardening
    - security
    - system
    - ubuntu
    - useradd
