---
galaxy_info:
  role_name: auditd
  author: konstruktoid
  description: Install and configure auditd and manage audit rules on AlmaLinux, Debian, and Ubuntu.
  license: apache
  min_ansible_version: "2.18"
  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: EL
      versions:
        - "9"
        - "10"
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - almalinux
    - centos
    - cis
    - debian
    - disa
    - hardening
    - security
    - system
    - systemd
    - ubuntu
