---
# Packages that will be removed from the system if they are installed.
packages_blocklist:
  - "apport"
  - "autofs"
  - "avahi"
  - "beep"
  - "ftp"
  - "git"
  - "inetutils-telnet"
  - "pastebinit"
  - "popularity-contest"
  - "prelink"
  - "rpcbind"
  - "rsh"
  - "rsh-server"
  - "rsync"
  - "talk"
  - "telnet"
  - "telnet-server"
  - "tftp"
  - "tftpd"
  - "tnftp"
  - "tuned"
  - "vsftpd"
  - "whoopsie"
  - "xinetd"
  - "yp-tools"
  - "ypbind"

# Packages to install on Debian-based systems.
packages_debian:
  - "acct"
  - "apparmor-profiles"
  - "apparmor-utils"
  - "apt-listchanges"
  - "apt-show-versions"
  - "audispd-plugins"
  - "auditd"
  - "cracklib-runtime"
  - "curl"
  - "debsums"
  - "gnupg2"
  - "libpam-apparmor"
  - "libpam-cap"
  - "libpam-modules"
  - "libpam-tmpdir"
  - "lsb-release"
  - "needrestart"
  - "openssh-server"
  - "postfix"
  - "rsyslog"
  - "sysstat"
  - "systemd-journal-remote"
  - "tcpd"
  - "vlock"
  - "wamerican"

# Packages to install on Red Hat-based systems.
packages_redhat:
  - "audispd-plugins"
  - "audit"
  - "cracklib"
  - "curl"
  - "gnupg2"
  - "openssh-server"
  - "postfix"
  - "psacct"
  - "python3-dnf-plugin-post-transaction-actions"
  - "rsyslog"
  - "rsyslog-gnutls"
  - "systemd-journal-remote"
  - "vlock"
  - "words"

# Packages to install on Ubuntu-based systems.
packages_ubuntu:
  - "fwupd"
  - "secureboot-db"
  - "snapd"
