---
argument_specs:
  main:
    short_description: "Kernel hardening."
    description:
      - "Kernel hardening."
    author:
      - "Thomas Sjögren (@konstruktoid)"
    options:
      allow_virtual_system_calls:
        description: "Allow virtual system calls (vsyscall). False sets vsyscall=none, the strictest option; very old binary-only software may need emulate."
        type: "bool"
        default: false
      enable_page_poisoning:
        description: "Enable kernel page poisoning."
        type: "bool"
        default: true
      kernel_lockdown:
        description: "Configures kernel_lockdown. confidentiality is the strictest mode."
        type: "str"
        default: "confidentiality"
        choices:
          - "confidentiality"
          - "False"
          - "integrity"
          - "none"
          - "True"
      page_table_isolation:
        description: "Enable page table isolation (PTI)."
        type: "bool"
        default: true
      slub_debugger_poisoning:
        description: "Enable SLUB debugger poisoning."
        type: "bool"
        default: true
