---
argument_specs:
  main:
    short_description: SSH installation and configuration.
    description:
      - SSH installation and configuration.
    author:
      - "Thomas Sjögren (@konstruktoid)"
    options:
      sshd_accept_env:
        description: "Specifies what environment variables sent by the client will be copied into the session."
        type: "str"
        default: "LANG LC_*"
      sshd_admin_net:
        description: "Only the network(s) defined in C(sshd_admin_net) are allowed to connect to C(sshd_ports)."
        type: "list"
        elements: "str"
        default: "['192.168.0.0/24', '192.168.1.0/24']"
      sshd_allow_agent_forwarding:
        description: "Specifies whether ssh-agent forwarding is permitted."
        type: "bool"
        default: "False"
      sshd_allow_groups:
        description: "If specified, login is allowed only for users whose primary group or supplementary group list matches one of the patterns."
        type: "list"
        elements: "str"
        default: "['sudo']"
      sshd_allow_tcp_forwarding:
        description: "Specifies whether TCP forwarding is permitted."
        type: "str"
        default: "False"
        choices:
          - "all"
          - "False"
          - "local"
          - "remote"
          - "True"
      sshd_allow_users:
        description: "If specified, login is allowed only for users whose user name matches one of the patterns."
        type: "list"
        elements: "str"
      sshd_authentication_methods:
        description: "The authentication methods that must be successfully completed in order to grant access to a user."
        type: "str"
        default: "any"
      sshd_authorized_principals_file:
        description: "Specifies a file that lists principal names that are accepted for certificate authentication."
        type: "path"
        default: "/etc/ssh/auth_principals/%u"
      sshd_banner:
        description: "The contents of the specified file are sent to the remote user before authentication."
        type: "path"
        default: "/etc/issue.net"
      sshd_ca_signature_algorithms:
        description: "Specifies which algorithms are allowed for signing of certificates by certificate authorities."
        type: "list"
        elements: "str"
        default: "['ecdsa-sha2-nistp384', 'ecdsa-sha2-nistp521', 'ssh-ed25519', 'rsa-sha2-512']"
      sshd_kbd_interactive_authentication:
        description: "Specifies whether to allow keyboard-interactive authentication."
        type: "bool"
        default: "False"
      sshd_ciphers:
        description: "Specifies the ciphers allowed. Multiple ciphers must be comma-separated."
        type: "list"
        elements: "str"
        default: "['chacha20-poly1305@openssh.com', 'aes256-gcm@openssh.com', 'aes256-ctr']"
      sshd_client_alive_count_max:
        description: "Sets the number of client alive messages which may be sent without sshd receiving any messages back from the client."
        type: "int"
        default: 1
      sshd_client_alive_interval:
        description: "Sets a timeout interval in seconds after which if no data has been received from the client, sshd will send a message channel to request a response from the client."
        type: "int"
        default: 200
      sshd_compression:
        description: "Specifies whether compression is enabled."
        type: "bool"
        default: "False"
      sshd_config_d_force_clear:
        description: "Clear pre-existing custom configurations in /etc/ssh/sshd_config.d"
        type: "bool"
        default: "False"
      sshd_config_force_replace:
        description: "Force replace configuration file C(/etc/ssh/sshd_config)."
        type: "bool"
        default: "False"
      sshd_debian_banner:
        description: "Specifies whether the distribution-specified extra version suffix is included during initial protocol handshake."
        type: "bool"
        default: "False"
      sshd_deny_groups:
        description: "Login is disallowed for users whose primary group or supplementary group list matches one of the patterns."
        type: "list"
        elements: "str"
        default: "[]"
      sshd_deny_users:
        description: "Login is disallowed for users whose user name matches one of the patterns."
        type: "list"
        elements: "str"
        default: "[]"
      sshd_gateway_ports:
        description: "Specifies whether remote hosts are allowed to connect to ports forwarded for the client."
        type: "bool"
        default: "False"
      sshd_gssapi_authentication:
        description: "Specifies whether user authentication based on GSSAPI is allowed."
        type: "bool"
        default: "False"
      sshd_host_key_algorithms:
        description: "Specifies the host key algorithms that the server offers."
        type: "list"
        elements: "str"
        default: "['ssh-ed25519-cert-v01@openssh.com', 'ssh-rsa-cert-v01@openssh.com', 'ssh-ed25519', 'ecdsa-sha2-nistp521-cert-v01@openssh.com', 'ecdsa-sha2-nistp384-cert-v01@openssh.com', 'ecdsa-sha2-nistp521',
          'ecdsa-sha2-nistp384']"
      sshd_host_keys_files:
        description: "Specifies a file containing a private host key used by SSH. If empty C(RSA), C(ECDSA), and C(ED25519) will be used, if supported by the installed sshd version."
        type: "list"
        elements: "str"
        default: "[]"
      sshd_host_keys_group:
        description: "Owner group of the host keys."
        type: "str"
        default: "root"
      sshd_host_keys_mode:
        description: "Host keys file mode."
        type: "str"
        default: "0600"
      sshd_host_keys_owner:
        description: "Owner of the host keys."
        type: "str"
        default: "root"
      sshd_hostbased_authentication:
        description: "Specifies whether rhosts or /etc/hosts.equiv authentication together with successful public key client host authentication is allowed."
        type: "bool"
        default: "False"
      sshd_ignore_rhosts:
        description: "Specifies that .rhosts and .shosts files will not be used in HostbasedAuthentication."
        type: "bool"
        default: "True"
      sshd_ignore_user_known_hosts:
        description: "Specifies whether sshd should ignore the user's ~/.ssh/known_hosts during HostbasedAuthentication and use only the system-wide known hosts file /etc/ssh/known_hosts."
        type: "bool"
        default: "True"
      sshd_kerberos_authentication:
        description: "Specifies whether the password provided by the user for PasswordAuthentication will be validated through the Kerberos KDC."
        type: "bool"
        default: "False"
      sshd_kex_algorithms:
        description: "Specifies the available KEX (Key Exchange) algorithms."
        type: "list"
        elements: "str"
        default: "['curve25519-sha256@libssh.org', 'diffie-hellman-group16-sha512', 'diffie-hellman-group18-sha512', 'ecdh-sha2-nistp521', 'ecdh-sha2-nistp384']"
      sshd_listen:
        description: "Specifies the addresses sshd should listen on."
        type: "list"
        elements: "str"
        default: "['0.0.0.0']"
      sshd_log_level:
        description: "Gives the verbosity level that is used when logging messages from sshd."
        type: "str"
        default: "verbose"
        choices:
          - "debug"
          - "debug1"
          - "debug2"
          - "debug3"
          - "error"
          - "fatal"
          - "info"
          - "quiet"
          - "verbose"
      sshd_login_grace_time:
        description: "The server disconnects after this time if the user has not successfully logged in."
        type: "int"
        default: 20
      sshd_macs:
        description: "Specifies the available MAC (Message Authentication Code) algorithms."
        type: "list"
        elements: "str"
        default: "['hmac-sha2-512-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512', 'hmac-sha2-256']"
      sshd_match_addresses:
        description: "Add a conditional block for addresses. If all of the criteria on the Match line are satisfied, the rules/parameters defined override those set in the global section of the
          config file, until either another Match line or the end of the file."
        type: "list"
      sshd_match_groups:
        description: "Add a conditional block for groups. If all of the criteria on the Match line are satisfied, the rules/parameters defined override those set in the global section of the config
          file, until either another Match line or the end of the file."
        type: "list"
      sshd_match_local_ports:
        description: "Add a conditional block for ports. If all of the criteria on the Match line are satisfied, the rules/parameters defined override those set in the global section of the config
          file, until either another Match line or the end of the file."
        type: "list"
      sshd_match_users:
        description: "Add a conditional block for users. If all of the criteria on the Match line are satisfied, the rules/parameters defined override those set in the global section of the config
          file, until either another Match line or the end of the file."
        type: "list"
      sshd_max_auth_tries:
        description: "Specifies the maximum number of authentication attempts permitted per connection."
        type: "int"
        default: 3
      sshd_max_sessions:
        description: "Specifies the maximum number of open sessions permitted per network connection."
        type: "int"
        default: 3
      sshd_max_startups:
        description: "Specifies the maximum number of concurrent unauthenticated connections to the SSH daemon."
        type: "str"
        default: "10:30:60"
      sshd_password_authentication:
        description: "Specifies whether password authentication is allowed."
        type: "bool"
        default: "False"
      sshd_permit_empty_passwords:
        description: "Specifies whether the server allows login to accounts with empty password strings."
        type: "bool"
        default: "False"
      sshd_permit_root_login:
        description: "Specifies whether root can log in using ssh, if True then the option is set to prohibit-password."
        type: "bool"
        default: "False"
      sshd_permit_tunnel:
        description: "Specifies whether tun device forwarding is allowed."
        type: "bool"
        default: "False"
      sshd_permit_user_environment:
        description: "Specifies whether user environment variables are processed by sshd."
        type: "bool"
        default: "False"
      sshd_ports:
        description: "Specifies the port number that sshd listens on."
        type: "list"
        elements: "int"
        default: "[22]"
      sshd_print_last_log:
        description: "Specifies whether sshd should print the last user login when a user logs in interactively."
        type: "bool"
        default: "True"
      sshd_print_motd:
        description: "Specifies whether sshd should print /etc/motd when a user logs in interactively."
        type: "bool"
        default: "False"
      sshd_print_pam_motd:
        description: "Specifies whether pam_motd should be enabled for sshd."
        type: "bool"
        default: "False"
      sshd_rekey_limit:
        description: "Specifies the maximum amount of data that may be transmitted before the session key is renegotiated, optionally followed a maximum amount of time that may pass before the
          session key is renegotiated."
        type: "str"
        default: "512M 1h"
      sshd_required_ecdsa_size:
        description: "Required ECDSA key size when generating new host keys."
        type: "int"
        default: 521
      sshd_required_rsa_size:
        description: "Required RSA key size when generating new host keys."
        type: "int"
        default: 4096
      sshd_sftp_enabled:
        description: "Specifies whether the SFTP subsystem should be enabled."
        type: "bool"
        default: "True"
      sshd_sftp_chroot:
        description: "Specifies whether the SFTP subsystem should chroot users."
        type: "bool"
        default: "True"
      sshd_sftp_chroot_dir:
        description: "Specifies the pathname of a directory to chroot to after authentication."
        type: "str"
        default: "%h"
      sshd_sftp_only_group:
        description: "Specifies the name of the group that will have access restricted to the sftp service only."
        type: "str"
        default: ""
      sshd_sftp_subsystem:
        description: "Specifies the SFTP subsystem to use."
        type: "str"
        default: "internal-sftp -f LOCAL6 -l INFO"
      sshd_strict_modes:
        description: "Specifies whether sshd should check file modes and ownership of the user's files and home directory before accepting login."
        type: "bool"
        default: "True"
      sshd_syslog_facility:
        description: "Gives the facility code that is used when logging messages from sshd."
        type: "str"
        default: "auth"
        choices:
          - "auth"
          - "daemon"
          - "user"
          - "local0"
          - "local1"
          - "local2"
          - "local3"
          - "local4"
          - "local5"
          - "local6"
          - "local7"
      sshd_tcp_keep_alive:
        description: "Specifies whether the system should send TCP keepalive messages to the other side."
        type: "bool"
        default: "False"
      sshd_trusted_user_ca_keys_base64:
        description: "Public keys of trusted certificate authoritites in base64 format."
        type: "str"
        default: ""
      sshd_trusted_user_ca_keys_file:
        description: "Specifies a file containing public keys of certificate authorities that are trusted to sign user certificates for authentication."
        type: "path"
        default: "/etc/ssh/trusted-user-ca-keys.pem"
      sshd_update_moduli:
        description: "Specifies whether the moduli file should be updated."
        type: "bool"
        default: "False"
      sshd_update_moduli_url:
        description: "Specifies the URL to download the moduli file from."
        type: "str"
        default: "https://raw.githubusercontent.com/konstruktoid/ssh-moduli/main/moduli"
      sshd_use_dns:
        description: "Specifies whether sshd should look up the remote host name, and to check that the resolved host name for the remote IP address maps back to the very same IP address."
        type: "bool"
        default: "False"
      sshd_use_pam:
        description: "If true, this will enable PAM authentication using KbdInteractiveAuthentication and PasswordAuthentication in addition to PAM account and session module processing for all
          authentication types."
        type: "bool"
        default: "True"
      sshd_use_privilege_separation:
        description: "Specifies whether sshd separates privileges by creating an unprivileged child process to deal with incoming network traffic."
        type: "str"
        default: "sandbox"
        choices:
          - "yes"
          - "no"
          - "sandbox"
      sshd_x11_forwarding:
        description: "Specifies whether X11 forwarding is permitted."
        type: "bool"
        default: "False"
      set_crypto_policies:
        description: "Set cryptographic policies to the specified value. This is only applicable on RHEL-based distributions that support crypto policies."
        type: "bool"
        default: "True"
