---
argument_specs:
  main:
    short_description: "Configure session timeout and umask settings for user sessions."
    description:
      - "This module configures session timeout and umask settings for user sessions."
      - "This modules sets the default umask value for user sessions."
    author:
      - "Thomas Sjögren (@konstruktoid)"
    options:
      umask_value:
        description: "Sets the default umask value."
        type: "int"
        default: "0077"
