---
- name: Stat available compilers
  become: true
  ansible.builtin.find:
    paths: [/usr/local/sbin, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /snap/bin]
    patterns: "{{ compilers }}"
    file_type: file
    follow: true
    recurse: true
    depth: 5
  register: compiler

- name: Restrict compilers access
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: "0750"
    state: file
    follow: true
  loop: "{{ compiler.files }}"

- name: Check dpkg-statoverride for restricted compilers access
  become: true
  ansible.builtin.command:
    cmd: dpkg-statoverride --list "{{ item.path }}"
  register: dpkg_statoverride_current
  changed_when: false
  failed_when: false
  loop: "{{ compiler.files }}"
  when:
    - ansible_facts.os_family == 'Debian'

- name: Ensure restrict compilers access via dpkg-statoverride
  become: true
  ansible.builtin.command:
    cmd: dpkg-statoverride --update --force-all --add root root 0750 "{{ item.path }}"
  loop: "{{ compiler.files }}"
  register: dpkg_statoverride_update
  changed_when: dpkg_statoverride_update.rc == 0
  loop_control:
    index_var: compiler_file_index
  when:
    - ansible_facts.os_family == 'Debian'
    - dpkg_statoverride_current.results[compiler_file_index].rc != 0 or dpkg_statoverride_current.results[compiler_file_index].stdout != 'root root 750 ' ~
      item.path

- name: Ensure DNF post-transaction-actions plugin is installed
  become: true
  ansible.builtin.package:
    name: python3-dnf-plugin-post-transaction-actions
    state: present
  when:
    - ansible_facts.os_family == 'RedHat'

- name: Ensure DNF post-transaction-actions plugin directory exists
  become: true
  ansible.builtin.file:
    path: /etc/dnf/plugins/post-transaction-actions.d
    state: directory
    owner: root
    group: root
    mode: "0755"
  when:
    - ansible_facts.os_family == 'RedHat'

- name: Ensure restrict compilers access via DNF post-transaction-actions Plugin
  ansible.builtin.include_tasks:
    file: compilers_dnf_post_transaction_actions_plugin.yml
  loop: "{{ compiler.files | map(attribute='path') | unique }}"
  when:
    - ansible_facts.os_family == 'RedHat'
