---
- name: Restart ssh socket
  become: true
  ansible.builtin.service:
    name: "{{ 'ssh.socket' if ansible_facts.os_family == 'Debian' else 'sshd.socket' }}"
    state: restarted
    enabled: true
  when:
    - ansible_facts.virtualization_type not in ["container", "docker", "podman"]
    - ansible_facts.distribution == "Ubuntu"

- name: Restart ssh service
  become: true
  ansible.builtin.service:
    name: "{{ 'ssh.service' if ansible_facts.os_family == 'Debian' else 'sshd.service' }}"
    state: restarted
    enabled: true
  when:
    - ansible_facts.virtualization_type not in ["container", "docker", "podman"]

- name: Disable ssh service
  become: true
  ansible.builtin.service:
    name: "{{ 'ssh.service' if ansible_facts.os_family == 'Debian' else 'sshd.service' }}"
    state: stopped
    enabled: false
  when:
    - ansible_facts.virtualization_type not in ["container", "docker", "podman"]
    - ansible_facts.distribution == "Ubuntu"
