---
conntrack_sysctl_settings:
  net.netfilter.nf_conntrack_max: 2000000 # The maximum number of connections that the system’s connection tracking table can hold at any time.
  net.netfilter.nf_conntrack_tcp_loose: 0 # If 0, the system will not allow TCP connections to be established without a SYN packet.

# If True, IPv6 support is disabled.
disable_ipv6: false

# Only the network(s) defined in C(ufw_admin_net) are allowed to connect to C(ufw_ports).
ufw_admin_net: ["192.168.0.0/24", "192.168.1.0/24"]
# Specifies the port number that ufw should listen on for incoming connections.
# This is typically used for SSH (port 22) or other services you want to allow access to.
ufw_ports: [22]
# Allowed outgoing ports and protocols.
ufw_outgoing_traffic:
  - { "port": 22, "proto": "tcp" }
  - 53
  - { "port": 80, "proto": "tcp" }
  - { "port": 123, "proto": "udp" }
  - { "port": 443, "proto": "tcp" }
  - 853
  - { "port": 4460, "proto": "tcp" }

# If True, rate limiting is enabled for incoming connections.
ufw_rate_limit: false
