---
- name: Verify
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: Reboot and reconnect
      when:
        - ansible_facts.virtualization_type not in ["container", "docker", "podman"]
      block:
        - name: Reboot host
          become: true
          ansible.builtin.reboot:

        - name: Wait for the host and reconnect
          ansible.builtin.wait_for:
            port: 22
            host: "{{ (ansible_facts.ssh_host | default(ansible_facts.host)) | default(inventory_hostname) }}"
            delay: 10
            timeout: 120

    - name: Include default vars
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions:
          - yml

    - name: Include host vars
      ansible.builtin.include_vars:
        file: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/inventory/host_vars/{{ ansible_facts.hostname }}"

    - name: Get installed sshd version
      environment:
        PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin/
      ansible.builtin.command:
        cmd: sshd -V
      changed_when: false
      failed_when: false
      check_mode: false
      register: sshd_version

    - name: Set ssh version as fact
      ansible.builtin.set_fact:
        ssh_installed_version: "{{ sshd_version.stderr_lines | regex_search('OpenSSH_([0-9+][0-9+].[0-9+]|[0-9+].[0-9]+)', '\\1') | first }}"

    - name: Ensure privilege separation directories exist
      become: true
      ansible.builtin.file:
        path: "{{ item.path }}"
        owner: root
        group: root
        state: directory
        mode: "{{ item.mode }}"
      register: privsep_dir
      failed_when:
        - privsep_dir is changed
        - not (item.path == '/run/sshd' and ansible_facts.distribution == 'Ubuntu')
      loop:
        - { path: /run/sshd, mode: "0755" }
        - { path: /usr/share/empty.sshd, mode: "0711" }
        - { path: /var/empty, mode: "0755" }
        - { path: /var/empty/sshd, mode: "0711" }

    - name: Stat /etc/ssh/sshd_config
      ansible.builtin.stat:
        path: /etc/ssh/sshd_config
      register: sshd_config_file

    - name: Stat /etc/ssh/ssh_config
      ansible.builtin.stat:
        path: /etc/ssh/ssh_config
      register: ssh_config_file

    - name: Stat /etc/ssh/sshd_config.d/01-hardening.conf
      become: true
      ansible.builtin.stat:
        path: /etc/ssh/sshd_config.d/01-hardening.conf
      register: sshd_config_directory

    - name: Assert /etc/ssh/ssh_config permissions
      ansible.builtin.assert:
        that:
          - ssh_config_file.stat.mode == "0644"
        success_msg: "{{ ssh_config_file.stat.path }} has correct permissions: {{ ssh_config_file.stat.mode }}"
        fail_msg: "{{ ssh_config_file.stat.path }} permissions are incorrect: {{ ssh_config_file.stat.mode }}"
      when:
        - ssh_config_file.stat.exists

    - name: Assert /etc/ssh/sshd_config permissions
      ansible.builtin.assert:
        that:
          - sshd_config_file.stat.mode == "0600"
        success_msg: "{{ sshd_config_file.stat.path }} has correct permissions: {{ sshd_config_file.stat.mode }}"
        fail_msg: "{{ sshd_config_file.stat.path }} permissions are incorrect: {{ sshd_config_file.stat.mode }}"
      when:
        - sshd_config_file.stat.exists

    - name: Assert /etc/ssh/sshd_config.d/01-hardening.conf permissions
      ansible.builtin.assert:
        that:
          - sshd_config_directory.stat.mode == "0600"
        success_msg: "{{ sshd_config_directory.stat.path }} has correct permissions: {{ sshd_config_directory.stat.mode }}"
        fail_msg: "{{ sshd_config_directory.stat.path }} permissions are incorrect: {{ sshd_config_directory.stat.mode }}"
      when:
        - sshd_config_directory.stat.exists

    - name: Verify sshd configuration
      block:
        - name: Verify sshd PermitRootLogin configuration
          become: true
          ansible.builtin.lineinfile:
            dest: /etc/ssh/sshd_config
            line: PermitRootLogin yes
            state: absent
          check_mode: true
          register: sshd_config
          failed_when: sshd_config is changed

        - name: Verify sshd_config.d PermitRootLogin configuration
          become: true
          ansible.builtin.lineinfile:
            dest: /etc/ssh/sshd_config.d/01-hardening.conf
            line: PermitRootLogin yes
            state: absent
          check_mode: true
          register: sshd_config_d
          failed_when: sshd_config_d is changed
          when:
            - sshd_config_directory.stat.exists

        - name: Set sshd_config_parameters
          ansible.builtin.set_fact:
            sshd_config_parameters:
              - >-
                {%- if sshd_accept_env | length > 0 -%}
                  AcceptEnv {{ sshd_accept_env }}
                {%- endif -%}
              - AddressFamily any
              - >-
                {%- if sshd_allow_groups | length > 0 -%}
                  {{ 'AllowGroups ' + sshd_allow_groups | join(' ') }}
                {%- endif -%}
              - >-
                {%- if sshd_allow_users | length > 0 -%}
                  {{ 'AllowUsers ' + sshd_allow_users | join(' ') }}
                {%- endif -%}
              - AllowAgentForwarding {{ 'yes' if (sshd_allow_agent_forwarding | bool) else 'no' }}
              - >-
                {%- if (ssh_installed_version is version('6.2', '>=')) -%}
                  {%- if sshd_allow_tcp_forwarding in ('yes', 'no', 'local', 'all', 'remote') -%}
                    AllowTcpForwarding {{ sshd_allow_tcp_forwarding }}
                {%- else -%}
                  AllowTcpForwarding {{ 'yes' if sshd_allow_tcp_forwarding | bool else 'no' }}
                {%- endif -%}
                {%- else -%}
                  {%- if sshd_allow_tcp_forwarding in ('yes', 'no') -%}
                    AllowTcpForwarding {{ sshd_allow_tcp_forwarding }}
                {%- else -%}
                  AllowTcpForwarding {{ 'yes' if sshd_allow_tcp_forwarding | bool else 'no' }}
                {%- endif -%}
                {%- endif -%}
              - >-
                {%- if sshd_authentication_methods | length > 0 and ssh_installed_version is version('6.2', '>=') -%}
                  AuthenticationMethods {{ sshd_authentication_methods }}
                {%- endif -%}
              - Banner {{ sshd_banner if sshd_banner else 'none' }}
              - >-
                {%- if not use_crypto_policies -%}
                  CASignatureAlgorithms {{ sshd_ca_signature_algorithms | join(',') }}
                {%- endif -%}
              - >-
                {%- if not use_crypto_policies -%}
                  Ciphers {{ sshd_ciphers | join(',') }}
                {%- endif -%}
              - >-
                {%- if sshd_client_alive_count_max -%}
                  ClientAliveCountMax {{ sshd_client_alive_count_max | int }}
                {%- endif -%}
              - >-
                {%- if sshd_client_alive_interval -%}
                  ClientAliveInterval {{ sshd_client_alive_interval | int }}
                {%- endif -%}
              - Compression {{ 'yes' if (sshd_compression | bool) else 'no' }}
              - >-
                {%- if ansible_facts.os_family == 'Debian' and sshd_debian_banner -%}
                    DebianBanner ('yes' if (sshd_debian_banner | bool) else 'no')
                {%- endif -%}
              - GSSAPIAuthentication {{ 'yes' if (sshd_gssapi_authentication | bool) else 'no' }}
              - GSSAPICleanupCredentials yes
              - HostbasedAuthentication {{ 'yes' if (sshd_hostbased_authentication | bool) else 'no' }}
              - >-
                {%- if not use_crypto_policies -%}
                  HostKeyAlgorithms {{ sshd_host_key_algorithms | join(',') }}
                {%- endif -%}
              - IgnoreRhosts {{ 'yes' if (sshd_ignore_rhosts | bool) else 'no' }}
              - IgnoreUserKnownHosts {{ 'yes' if (sshd_ignore_user_known_hosts | bool) else 'no' }}
              - >-
                {%- if ssh_installed_version is version('8.7', '>=') -%}
                  KbdInteractiveAuthentication {{ 'yes' if (sshd_kbd_interactive_authentication | bool) else 'no' }}
                {%- else -%}
                  ChallengeResponseAuthentication {{ 'yes' if (sshd_kbd_interactive_authentication | bool) else 'no' }}
                {%- endif -%}
              - KerberosAuthentication {{ 'yes' if (sshd_kerberos_authentication | bool) else 'no' }}
              - >-
                {%- if not use_crypto_policies -%}
                  KexAlgorithms {{ sshd_kex_algorithms | join(',') }}
                {%- endif -%}
              - >-
                {%- if sshd_log_level | length > 0 -%}
                  LogLevel {{ sshd_log_level | upper }}
                {%- endif -%}
              - >-
                {%- if sshd_login_grace_time is not none -%}
                  LoginGraceTime {{ sshd_login_grace_time | int }}
                {%- endif -%}
              - >-
                {%- if not use_crypto_policies -%}
                  MACs {{ sshd_macs | join(',') }}
                {%- endif -%}
              - >-
                {%- if sshd_max_auth_tries -%}
                  MaxAuthTries {{ sshd_max_auth_tries | int }}
                {%- endif -%}
              - >-
                {%- if sshd_max_sessions -%}
                  MaxSessions {{ sshd_max_sessions | int }}
                {%- endif -%}
              - >-
                {% if sshd_max_startups -%}
                  MaxStartups {{ sshd_max_startups }}
                {%- endif -%}
              - PasswordAuthentication {{ 'yes' if (sshd_password_authentication | bool) else 'no' }}
              - PermitEmptyPasswords {{ 'yes' if (sshd_permit_empty_passwords | bool) else 'no' }}
              - PermitRootLogin {{ 'yes' if (sshd_permit_root_login | bool) else 'no' }}
              - PermitTunnel {{ 'yes' if (sshd_permit_tunnel | bool) else 'no' }}
              - PermitUserEnvironment {{ 'yes' if (sshd_permit_user_environment | bool) else 'no' }}
              - PrintLastLog {{ 'yes' if (sshd_print_last_log | bool) else 'no' }}
              - PrintMotd {{ 'yes' if (sshd_print_motd | bool) else 'no' }}
              - >-
                {%- if ssh_installed_version is version('7.6', '<') -%}
                  Protocol 2
                {%- endif -%}
              - PubkeyAuthentication yes
              - >-
                {%- if sshd_rekey_limit | length > 0 -%}
                  RekeyLimit {{ sshd_rekey_limit }}
                {%- endif -%}
              - >-
                {%- if ssh_installed_version is version('9.1', '>') and not use_crypto_policies -%}
                    RequiredRSASize {{ sshd_required_rsa_size | int }}
                {%- endif -%}
              - StrictModes {{ 'yes' if (sshd_strict_modes | bool) else 'no' }}
              - >-
                {%- if sshd_sftp_subsystem | length > 0 and sshd_sftp_enabled -%}
                  Subsystem sftp {{ sshd_sftp_subsystem }}
                {%- endif -%}
              - >-
                {%- if sshd_syslog_facility | length > 0 -%}
                  SyslogFacility {{ sshd_syslog_facility | upper }}
                {%- endif -%}
              - TCPKeepAlive {{ 'yes' if (sshd_tcp_keep_alive | bool) else 'no' }}
              - UseDNS {{ 'yes' if (sshd_use_dns | bool) else 'no' }}
              - >-
                {%- if ssh_installed_version is version('7.4', '<') -%}
                  UseLogin no
                {%- endif -%}
              - UsePAM {{ 'yes' if sshd_use_pam | bool else 'no' }}
              - >-
                {%- if ssh_installed_version is version('7.5', '<') -%}
                  {%- if sshd_use_privilege_separation in ('yes', 'no', 'sandbox') -%}
                    UsePrivilegeSeparation {{ sshd_use_privilege_separation }}
                {%- else -%}
                  UsePrivilegeSeparation {{ 'yes' if (sshd_use_privilege_separation | bool) else 'no' }}
                {%- endif -%}
                {%- endif -%}
              - X11Forwarding {{ 'yes' if (sshd_x11_forwarding | bool) else 'no' }}
              - X11UseLocalhost yes

        - name: Set repeating parameters and clear empty values in sshd_config_parameters
          vars:
            _hostkey: "{{ ['HostKey '] | product(sshd_host_keys_files) | map('join') | list }}"
            _listenaddress: "{{ ['ListenAddress '] | product(sshd_listen) | map('join') | list }}"
            _port: "{{ ['Port '] | product(sshd_ports) | map('join') | list }}"
          ansible.builtin.set_fact:
            sshd_config_parameters: "{{ (sshd_config_parameters + _hostkey + _listenaddress + _port) | select() }}"

        - name: Verify sshd configuration
          become: true
          ansible.builtin.lineinfile:
            dest: /etc/ssh/sshd_config
            line: "{{ item }}"
            state: present
          check_mode: true
          register: sshd_config
          failed_when: sshd_config is changed
          loop: "{{ sshd_config_parameters }}"
          when:
            - not sshd_config_directory.stat.exists

        - name: Verify sshd config.d configuration
          become: true
          ansible.builtin.lineinfile:
            dest: /etc/ssh/sshd_config.d/01-hardening.conf
            line: "{{ item }}"
            state: present
          check_mode: true
          register: sshd_config
          failed_when: sshd_config is changed
          loop: "{{ sshd_config_parameters }}"
          when:
            - sshd_config_directory.stat.exists

        - name: Set parameters for runtime check
          ansible.builtin.set_fact:
            sshd_config_parameters_runtime: >-
              {{
                sshd_config_parameters_runtime | default([]) +
                [(item.split(' ')[0] | lower) + ' ' + (item.split(' ')[1:] | join(' '))]
              }}
          loop: "{{ sshd_config_parameters }}"

        - name: Set multiple parameters in runtime checking
          ansible.builtin.set_fact:
            sshd_config_parameters_runtime: >-
              {{
                ( sshd_config_parameters_runtime | reject('regex', '^' + item + ' ') | list ) +
                ( [item + ' '] |
                  product( sshd_config_parameters_runtime |
                           select('match', '^' + item + ' ') |
                           map('split', ' ', 1) |
                           map('last') |
                           map('split', ' ') |
                           unique |
                           flatten ) |
                  map('join') | list )
              }}
          loop:
            - allowgroups
            - acceptenv

        - name: Ignore parameters for runtime check
          ansible.builtin.set_fact:
            sshd_config_parameters_runtime: "{{ (sshd_config_parameters_runtime | reject('regex', '^' + item + ' ') | list) }}"
          loop:
            # debianbanner: not show in runtime.
            - debianbanner
            # listenaddress: runtime returns values addresses and ports(Ex: 0.0.0.0:22), ports is optional and can have multiple values.
            - listenaddress
            # rekeylimit: runtime returns values only in bytes and seconds, having to treat these values would be a lot of work.
            - rekeylimit

        - name: Print sshd_config_parameters_runtime
          ansible.builtin.debug:
            msg: "{{ sshd_config_parameters_runtime }}"

        - name: Verify sshd runtime configuration
          become: true
          environment:
            PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          ansible.builtin.command:
            cmd: sshd -T
          check_mode: false
          register: sshd_config
          changed_when: false
          failed_when: item not in sshd_config.stdout_lines
          loop: "{{ sshd_config_parameters_runtime }}"

        - name: Verify ssh client configuration
          become: true
          ansible.builtin.lineinfile:
            dest: /etc/ssh/ssh_config
            line: "    {{ item }}"
            state: present
          check_mode: true
          register: ssh_config
          failed_when: ssh_config is changed
          loop:
            - GSSAPIAuthentication {{ 'yes' if (sshd_gssapi_authentication | bool) else 'no' }}
            - HashKnownHosts yes
            - RekeyLimit {{ sshd_rekey_limit }}
