---
galaxy_info:
  role_name: ufw
  author: konstruktoid
  description: "An Ansible role to manage UFW (Uncomplicated Firewall) rules."
  license: apache
  min_ansible_version: "2.18"
  platforms:
    - name: Debian
      versions:
        - trixie
    - name: EL
      versions:
        - "10"
    - name: Ubuntu
      versions:
        - resolute
  galaxy_tags:
    - almalinux
    - cis
    - debian
    - disa
    - hardening
    - security
    - ubuntu
    - ufw
