---
- name: Mask apport
  become: true
  ansible.builtin.systemd_service:
    name: apport.service
    masked: true
    enabled: false
    state: stopped
  register: apport_mask_result
  failed_when:
    - apport_mask_result is failed
    - "'Could not find the requested service apport.service' not in apport_mask_result.msg | default('')"
  when:
    - ansible_facts.virtualization_type not in ["container", "docker", "podman"]
