---
# login.defs configuration options.
login_defs:
  home_mode: "0700" # The permissions assigned to a newly created user's home directory.
  login_retries: 5 # Maximum number of login retries in case of bad password.
  login_timeout: 60 # Max time in seconds for login.
  pass_max_days: 60 # The maximum number of days a password may be used. If the password is older than this, a password change will be forced.
  pass_min_days: 1 # The minimum number of days allowed between password changes.
  pass_min_length: 15 # The minimum length of the new password.
  pass_warn_age: 7 # The number of days before password expiration that the user will be warned about the impending expiration.
  umask_value: "0077" # Sets the default umask value.
  usergroups_enabled: true # If True, userdel will remove the user's group if it's empty, and useradd will create by default a group with the name of the user.

# /etc/login.defs template location.
login_defs_template: "etc/login.defs.j2"
