---
# Filesystem kernel modules to block and blacklist.
fs_modules_blocklist:
  - "cramfs"
  - "freevxfs"
  - "hfs"
  - "hfsplus"
  - "jffs2"
  - "squashfs"
  - "udf"

# Misc kernel modules to block and blacklist.
misc_modules_blocklist:
  - "algif_aead"
  - "bluetooth"
  - "bnep"
  - "btusb"
  - "can"
  - "cpia2"
  - "esp4"
  - "esp6"
  - "firewire-core"
  - "floppy"
  - "ksmbd"
  - "n_hdlc"
  - "net-pf-31"
  - "pcspkr"
  - "rxrpc"
  - "soundcore"
  - "thunderbolt"
  - "usb-midi"
  - "usb-storage"
  - "uvcvideo"
  - "v4l2_common"

# Network kernel modules to block and blacklist.
net_modules_blocklist:
  - "atm"
  - "dccp"
  - "sctp"
  - "rds"
  - "tipc"
