---
- name: Verify
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: Reboot and reconnect
      when:
        - ansible_facts.virtualization_type not in ["container", "docker", "podman"]
      block:
        - name: Reboot host
          become: true
          ansible.builtin.reboot:

        - name: Wait for the host and reconnect
          ansible.builtin.wait_for:
            port: 22
            host: "{{ (ansible_facts.ssh_host | default(ansible_facts.host)) | default(inventory_hostname) }}"
            delay: 10
            timeout: 120

    - name: Include default vars
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions:
          - yml

    - name: Include host vars
      ansible.builtin.include_vars:
        file: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/inventory/host_vars/{{ ansible_facts.hostname }}"

    - name: Verify apt hardening configuration
      when:
        - ansible_facts.os_family == "Debian"
      block:
        - name: Stat apt hardening configuration file
          become: true
          ansible.builtin.stat:
            path: /etc/apt/apt.conf.d/98-hardening-ubuntu
          register: package_management_apt_hardening_configuration

        - name: Assert apt hardening configuration file exists
          ansible.builtin.assert:
            that:
              - package_management_apt_hardening_configuration.stat.exists
              - package_management_apt_hardening_configuration.stat.mode == "0644"

        - name: Read apt hardening configuration
          become: true
          ansible.builtin.slurp:
            path: /etc/apt/apt.conf.d/98-hardening-ubuntu
          register: package_management_apt_hardening_content

        - name: Set apt hardening options from file content
          ansible.builtin.set_fact:
            package_management_apt_hardening_options: >-
              {{
                package_management_apt_hardening_content.content
                | b64decode
                | splitlines()
                | reject("match", "^#|^$")
                | list
              }}

        - name: Assert apt hardening options
          ansible.builtin.assert:
            that:
              - item in package_management_apt_hardening_options
          loop: "{{ apt_options }}"

    - name: Verify yum.conf hardening settings
      when:
        - ansible_facts.os_family == "RedHat"
      block:
        - name: Read yum.conf settings
          become: true
          ansible.builtin.slurp:
            path: /etc/yum.conf
          register: package_management_yum_conf_content

        - name: Set yum.conf settings from file content
          ansible.builtin.set_fact:
            package_management_yum_conf_settings: >-
              {{
                package_management_yum_conf_content.content
                | b64decode
                | splitlines()
                | select("match", "^(gpgcheck|localpkg_gpgcheck|repo_gpgcheck|clean_requirements_on_remove)=")
                | list
              }}

        - name: Assert yum.conf hardening settings
          ansible.builtin.assert:
            that:
              - "'gpgcheck=1' in package_management_yum_conf_settings"
              - "'localpkg_gpgcheck=1' in package_management_yum_conf_settings"
              - "'repo_gpgcheck=1' in package_management_yum_conf_settings"
              - "'clean_requirements_on_remove=True' in package_management_yum_conf_settings"
