---
- name: Verify
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: Reboot and reconnect
      when:
        - ansible_facts.virtualization_type not in ["container", "docker", "podman"]
      block:
        - name: Reboot host
          become: true
          ansible.builtin.reboot:

        - name: Wait for the host and reconnect
          ansible.builtin.wait_for:
            port: 22
            host: "{{ (ansible_facts.ssh_host | default(ansible_facts.host)) | default(inventory_hostname) }}"
            delay: 10
            timeout: 120

    - name: Include default vars
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions:
          - yml

    - name: Include host vars
      ansible.builtin.include_vars:
        file: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/inventory/host_vars/{{ ansible_facts.hostname }}"

    - name: Verify apt hardening configuration
      when:
        - ansible_facts.os_family == "Debian"
      block:
        - name: Stat apt hardening configuration file
          become: true
          ansible.builtin.stat:
            path: /etc/apt/apt.conf.d/98-hardening-ubuntu
          register: package_management_apt_hardening_configuration

        - name: Assert apt hardening configuration file exists
          ansible.builtin.assert:
            that:
              - package_management_apt_hardening_configuration.stat.exists
              - package_management_apt_hardening_configuration.stat.mode == "0644"

    - name: Verify apt hardening settings
      become: true
      ansible.builtin.shell:
        cmd: grep -oE '^{{ item }}' /etc/apt/apt.conf.d/98-hardening-ubuntu
      args:
        executable: /bin/bash
      when:
        - ansible_facts.os_family == "Debian"
      changed_when: false
      loop:
        - 'Acquire::AllowDowngradeToInsecureRepositories "false";'
        - 'Acquire::AllowInsecureRepositories "false";'
        - 'Acquire::http::AllowRedirect "false";'
        - 'APT::Get::AllowUnauthenticated "false";'
        - 'APT::Get::AutomaticRemove "true";'
        - 'APT::Install-Recommends "false";'
        - 'APT::Install-Suggests "false";'
        - 'APT::Periodic::AutocleanInterval "7";'
        - 'APT::Sandbox::Seccomp "1";'
        - 'Unattended-Upgrade::Remove-Unused-Dependencies "true";'
        - 'Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";'

    - name: Verify yum.conf hardening settings
      become: true
      ansible.builtin.shell:
        cmd: grep -oE '^{{ item }}' /etc/yum.conf
      args:
        executable: /bin/bash
      changed_when: false
      when:
        - ansible_facts.os_family == "RedHat"
      loop:
        - "gpgcheck=1"
        - "localpkg_gpgcheck=1"
        - "repo_gpgcheck=1"
        - "clean_requirements_on_remove=True"
