---
argument_specs:
  main:
    short_description: Package management for hardening.
    description:
      - This role manages packages, it can remove potentially vulnerable packages and install necessary security-related packages based on the operating system.
    author:
      - konstruktoid
    options:
      packages_blocklist:
        description: "Packages that will be removed from the system if they are installed."
        type: "list"
        elements: "str"
        default:
          - "apport"
          - "autofs"
          - "avahi"
          - "beep"
          - "ftp"
          - "git"
          - "inetutils-telnet"
          - "pastebinit"
          - "popularity-contest"
          - "prelink"
          - "rpcbind"
          - "rsh"
          - "rsh-server"
          - "rsync"
          - "talk"
          - "telnet"
          - "telnet-server"
          - "tftp"
          - "tftpd"
          - "tnftp"
          - "tuned"
          - "vsftpd"
          - "whoopsie"
          - "xinetd"
          - "yp-tools"
          - "ypbind"
      packages_debian:
        description: "Packages to install on Debian-based systems."
        type: "list"
        elements: "str"
        default:
          - "acct"
          - "apparmor-profiles"
          - "apparmor-utils"
          - "apt-listchanges"
          - "apt-show-versions"
          - "audispd-plugins"
          - "auditd"
          - "cracklib-runtime"
          - "curl"
          - "debsums"
          - "gnupg2"
          - "libpam-apparmor"
          - "libpam-cap"
          - "libpam-modules"
          - "libpam-tmpdir"
          - "lsb-release"
          - "needrestart"
          - "openssh-server"
          - "postfix"
          - "rsyslog"
          - "sysstat"
          - "systemd-journal-remote"
          - "tcpd"
          - "vlock"
          - "wamerican"
      packages_redhat:
        description: "Packages to install on Red Hat-based systems."
        type: "list"
        elements: "str"
        default:
          - "audispd-plugins"
          - "audit"
          - "cracklib"
          - "curl"
          - "gnupg2"
          - "openssh-server"
          - "postfix"
          - "psacct"
          - "python3-dnf-plugin-post-transaction-actions"
          - "rsyslog"
          - "rsyslog-gnutls"
          - "systemd-journal-remote"
          - "vlock"
          - "words"
      packages_ubuntu:
        description: "Packages to install on Ubuntu-based systems."
        type: "list"
        elements: "str"
        default:
          - "fwupd"
          - "secureboot-db"
          - "snapd"
