---
- name: Verify
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: Reboot and reconnect
      when:
        - ansible_facts.virtualization_type not in ["container", "docker", "podman"]
      block:
        - name: Reboot host
          become: true
          ansible.builtin.reboot:

        - name: Wait for the host and reconnect
          ansible.builtin.wait_for:
            port: 22
            host: "{{ (ansible_facts.ssh_host | default(ansible_facts.host)) | default(inventory_hostname) }}"
            delay: 10
            timeout: 120

    - name: Include default vars
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions:
          - yml

    - name: Include host vars
      ansible.builtin.include_vars:
        file: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/inventory/host_vars/{{ ansible_facts.hostname }}"

    - name: Read /etc/hosts.allow
      ansible.builtin.command:
        cmd: grep -vE '^#|^$' /etc/hosts.allow
      register: hosts_allow
      changed_when: false

    - name: Assert hosts.allow entries
      ansible.builtin.assert:
        that:
          - "'sshd: ALL' in hosts_allow.stdout"
          - "'ALL: LOCAL, 127.0.0.1, [::1]' in hosts_allow.stdout"

    - name: Read /etc/hosts.deny
      ansible.builtin.command:
        cmd: grep -vE '^#|^$' /etc/hosts.deny
      register: hosts_deny
      changed_when: false

    - name: Assert hosts.deny entries
      ansible.builtin.assert:
        that:
          - "'ALL: ALL' in hosts_deny.stdout"
