---
on: [push, pull_request]
name: Ansible Lint
permissions: {}
concurrency:
  group: lint-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ansible-lint:
    runs-on: ubuntu-26.04
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c  # v2.21.0
        with:
          egress-policy: block
          allowed-endpoints: >
            azure.archive.ubuntu.com:80
            dl.google.com:443
            esm.ubuntu.com:443
            files.pythonhosted.org:443
            github.com:443
            motd.ubuntu.com:443
            packages.microsoft.com:443
            pypi.org:443
            raw.githubusercontent.com:443
            releases.astral.sh:443
            *.actions.githubusercontent.com:443
            *.blob.core.windows.net:443

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: Install system dependencies
        run: |
          sudo apt-get --assume-yes --update --no-install-recommends install python3-pip
          python3 -m pip install --user -U jmespath passlib

      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint@665d9e07a1943254d2910faffc106adaf7ea7294  # v26.8.0
        with:
          requirements_file: "requirements.yml"
