---
- name: Verify
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: Reboot and reconnect
      when:
        - ansible_facts.virtualization_type not in ["container", "docker", "podman"]
      block:
        - name: Reboot host
          become: true
          ansible.builtin.reboot:

        - name: Wait for the host and reconnect
          ansible.builtin.wait_for:
            port: 22
            host: "{{ (ansible_facts.ssh_host | default(ansible_facts.host)) | default(inventory_hostname) }}"
            delay: 10
            timeout: 120

    - name: Include default vars
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions:
          - yml

    - name: Include host vars
      ansible.builtin.include_vars:
        file: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/inventory/host_vars/{{ ansible_facts.hostname }}"

    - name: Ensure nmcli is available
      ansible.builtin.command:
        cmd: which nmcli
      register: nmcli_check
      changed_when: false
      failed_when: false

    - name: Verify Wi-Fi radio is disabled
      environment:
        PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      ansible.builtin.command:
        cmd: nmcli -t radio wifi
      register: wifi_radio_state
      changed_when: false
      failed_when: wifi_radio_state.stdout | trim != 'disabled'
      when:
        - nmcli_check.rc == 0
        - ansible_facts.virtualization_type not in ["container", "docker", "podman"]

    - name: Verify WWAN radio is disabled
      environment:
        PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      ansible.builtin.command:
        cmd: nmcli -t radio wwan
      register: wwan_radio_state
      changed_when: false
      failed_when: wwan_radio_state.stdout | trim != 'disabled'
      when:
        - nmcli_check.rc == 0
        - ansible_facts.virtualization_type not in ["container", "docker", "podman"]
